export interface IUserProfile {
    userId: string
    firstName: string
    lastName: string
    phone: string
    createdDate: string
    profileImage: string
    district: number
    block: number
    ci: number
    gp: number
    school: number
    medium: string
    classId: number
    photoType: string
    photoStream: string
    validTill: string
    className: string
    active: boolean
    userType: string
    email: string
    password: string
    userRole: string
    validityStatus: boolean
    sim1: string
    sim2: string
    createdDateString: string
    createdTimeString: string
}